### ISSUE TITLE
Go-live to-do list

### ISSUE THREAD

**Issue by Pieter-JanRobrechtCronos** [Unlock-d/unlockd_bluetooth#9]
- [ ] GitHub workflow to publish to pub.dev
- [ ] Determine licence
- [ ] Create small example which can be used easily for testing out new adapters
- [ ] Make sure the Unlock'd account is [verified][verified publisher] before publishing

For the core package:
- [ ] Update [pubspec file][pubspec docs]
- [ ] Update readme

[pubspec docs]: https://dart.dev/tools/pub/pubspec
[verified publisher]: https://dart.dev/tools/pub/publishing#create-verified-publisher
